#ifndef VISPUBLICCONTROLSUI_GLOBAL_H
#define VISPUBLICCONTROLSUI_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VISPUBLICCONTROLSUI_LIB
# define VISPUBLICCONTROLSUI_EXPORT Q_DECL_EXPORT
#else
# define VISPUBLICCONTROLSUI_EXPORT Q_DECL_IMPORT
#endif

#endif // VISPUBLICCONTROLSUI_GLOBAL_H
