#ifndef VISQTUITOOL_GLOBAL_H
#define VISQTUITOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VISQTUITOOL_LIB
# define VISQTUITOOL_EXPORT Q_DECL_EXPORT
#else
# define VISQTUITOOL_EXPORT Q_DECL_IMPORT
#endif

#endif // VISQTUITOOL_GLOBAL_H
